// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6HpGVnbFIX9SDdxN9mcLU_8p59i8ebVw',
    appId: '1:574248960561:android:f3791cfcf33b3feddecb10',
    messagingSenderId: '574248960561',
    projectId: 'flutter-instagram-clone-1b374',
    storageBucket: 'flutter-instagram-clone-1b374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAxksX0NWq1-Q8KxrW3-AUNimpjdkdLU',
    appId: '1:574248960561:ios:449480207bb11bdcdecb10',
    messagingSenderId: '574248960561',
    projectId: 'flutter-instagram-clone-1b374',
    storageBucket: 'flutter-instagram-clone-1b374.firebasestorage.app',
    iosClientId: '574248960561-gqvgpjsq0rq883iso9gfg33nn5r7k4do.apps.googleusercontent.com',
    iosBundleId: 'com.gambley1.flutterInstagramClone.dev',
  );
}
