// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsg3vDYr0o_0coqf7IQM6lMXH2d_vT2Ek',
    appId: '1:1025167484448:android:0314bd31be7c4c9e56fe45',
    messagingSenderId: '1025167484448',
    projectId: 'flutter-instagram-clone-7283d',
    storageBucket: 'flutter-instagram-clone-7283d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRHmHubprrKvcwVv-KwSsQSOKi2-jAd0',
    appId: '1:1025167484448:ios:9b29d85732ed95f956fe45',
    messagingSenderId: '1025167484448',
    projectId: 'flutter-instagram-clone-7283d',
    storageBucket: 'flutter-instagram-clone-7283d.firebasestorage.app',
    iosClientId: '1025167484448-f3l58ms8a8b9que5qidtqu1utgbeilig.apps.googleusercontent.com',
    iosBundleId: 'com.gambley1.flutterInstagramClone',
  );
}
