name: Build and Release APK

on:
  push:
    tags:
      - "v*" # Triggers when pushing a tag like v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "4.0.0-0.0.pre"  # Valid pre-release version for beta channel
          channel: beta

      - name: Upgrade Flutter and Verify Dart Version
        run: |
          flutter upgrade
          dart --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-release.apk
          body: "Automated release generated by GitHub Actions."
          draft: false
          prerelease: false
